// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearAll() {
    return $Call.ByID(1477534811);
}

/**
 * @returns {$CancellablePromise<string[]>}
 */
export function GetFileList() {
    return $Call.ByID(3051582047).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<[string, string]>}
 */
export function GetFolderState() {
    return $Call.ByID(817142114);
}

/**
 * @param {string} key
 * @param {any} v
 * @returns {$CancellablePromise<void>}
 */
export function GetJSON(key, v) {
    return $Call.ByID(3788061839, key, v);
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetSetting(key) {
    return $Call.ByID(1004933799, key);
}

/**
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function GetState(key) {
    return $Call.ByID(2978103138, key);
}

/**
 * @returns {$CancellablePromise<$models.TabRecord[]>}
 */
export function GetTabs() {
    return $Call.ByID(1563880513).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AppState | null>}
 */
export function LoadAppState() {
    return $Call.ByID(95983839).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function SaveFileList(paths) {
    return $Call.ByID(4014650876, paths);
}

/**
 * @param {string} folderPath
 * @param {string} treeJSON
 * @returns {$CancellablePromise<void>}
 */
export function SaveFolderState(folderPath, treeJSON) {
    return $Call.ByID(3800589999, folderPath, treeJSON);
}

/**
 * @param {string} key
 * @param {any} v
 * @returns {$CancellablePromise<void>}
 */
export function SaveJSON(key, v) {
    return $Call.ByID(2451643596, key, v);
}

/**
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SaveSetting(key, value) {
    return $Call.ByID(3045362270, key, value);
}

/**
 * @param {string} key
 * @param {string} value
 * @returns {$CancellablePromise<void>}
 */
export function SaveState(key, value) {
    return $Call.ByID(2829647991, key, value);
}

/**
 * @param {$models.TabRecord[]} tabs
 * @returns {$CancellablePromise<void>}
 */
export function SaveTabs(tabs) {
    return $Call.ByID(1498286342, tabs);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Shutdown() {
    return $Call.ByID(1722966973);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.TabRecord.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.AppState.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
