// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateFile creates a new markdown file and returns its path.
 * @param {string} dirPath
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function CreateFile(dirPath, name) {
    return $Call.ByID(2546163157, dirPath, name);
}

/**
 * CreateFolder creates a new directory and returns its path.
 * @param {string} parentPath
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function CreateFolder(parentPath, name) {
    return $Call.ByID(3768109919, parentPath, name);
}

/**
 * DeleteFile deletes a file or directory (recursively for directories).
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFile(path) {
    return $Call.ByID(2365823150, path);
}

/**
 * GetFileInfo returns file metadata.
 * @param {string} path
 * @returns {$CancellablePromise<$models.FileInfo | null>}
 */
export function GetFileInfo(path) {
    return $Call.ByID(1258000407, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetFilesInDir returns .md files directly in a directory (non-recursive).
 * @param {string} dirPath
 * @returns {$CancellablePromise<$models.FileNode[]>}
 */
export function GetFilesInDir(dirPath) {
    return $Call.ByID(3035331566, dirPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ListFiles returns all .md files recursively as a tree.
 * @param {string} rootPath
 * @returns {$CancellablePromise<$models.FileNode[]>}
 */
export function ListFiles(rootPath) {
    return $Call.ByID(2688665786, rootPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * OpenFile opens a native file picker dialog for .md files and returns the selected path.
 * @returns {$CancellablePromise<string>}
 */
export function OpenFile() {
    return $Call.ByID(236736201);
}

/**
 * OpenFolder opens a native directory picker dialog and returns the selected path.
 * @returns {$CancellablePromise<string>}
 */
export function OpenFolder() {
    return $Call.ByID(1413846947);
}

/**
 * OpenMultipleFiles opens a native file picker for .md files, allowing multiple selection.
 * @returns {$CancellablePromise<string[]>}
 */
export function OpenMultipleFiles() {
    return $Call.ByID(3692456474).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ReadFile reads a file's content as string.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(path) {
    return $Call.ByID(2175039153, path);
}

/**
 * SaveFile writes content to a file.
 * @param {string} path
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveFile(path, content) {
    return $Call.ByID(75167776, path, content);
}

// Private type creation functions
const $$createType0 = $models.FileInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.FileNode.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($Create.Any);
