// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Parse converts raw markdown string to HTML with metadata.
 * @param {string} raw
 * @returns {$CancellablePromise<$models.ParseResult | null>}
 */
export function Parse(raw) {
    return $Call.ByID(2890450715, raw).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ParseFile reads a file and parses it.
 * @param {string} filePath
 * @returns {$CancellablePromise<$models.ParseResult | null>}
 */
export function ParseFile(filePath) {
    return $Call.ByID(3717294037, filePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ParseResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
