// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class AppState {
    /**
     * Creates a new AppState instance.
     * @param {Partial<AppState>} [$$source = {}] - The source object to create the AppState.
     */
    constructor($$source = {}) {
        if (!("fileList" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["fileList"] = [];
        }
        if (!("tabs" in $$source)) {
            /**
             * @member
             * @type {TabRecord[]}
             */
            this["tabs"] = [];
        }
        if (!("activeTabId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeTabId"] = "";
        }
        if (!("folderPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folderPath"] = "";
        }
        if (!("folderTree" in $$source)) {
            /**
             * JSON string of FileNode[]
             * @member
             * @type {string}
             */
            this["folderTree"] = "";
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["language"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppState}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fileList" in $$parsedSource) {
            $$parsedSource["fileList"] = $$createField0_0($$parsedSource["fileList"]);
        }
        if ("tabs" in $$parsedSource) {
            $$parsedSource["tabs"] = $$createField1_0($$parsedSource["tabs"]);
        }
        return new AppState(/** @type {Partial<AppState>} */($$parsedSource));
    }
}

export class FileInfo {
    /**
     * Creates a new FileInfo instance.
     * @param {Partial<FileInfo>} [$$source = {}] - The source object to create the FileInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["modTime"] = null;
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["exists"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo(/** @type {Partial<FileInfo>} */($$parsedSource));
    }
}

export class FileNode {
    /**
     * Creates a new FileNode instance.
     * @param {Partial<FileNode>} [$$source = {}] - The source object to create the FileNode.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("isDir" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDir"] = false;
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["modTime"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FileNode[] | undefined}
             */
            this["children"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileNode}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField5_0($$parsedSource["children"]);
        }
        return new FileNode(/** @type {Partial<FileNode>} */($$parsedSource));
    }
}

export class ParseResult {
    /**
     * Creates a new ParseResult instance.
     * @param {Partial<ParseResult>} [$$source = {}] - The source object to create the ParseResult.
     */
    constructor($$source = {}) {
        if (!("html" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["html"] = "";
        }
        if (!("metadata" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParseResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ParseResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField1_0($$parsedSource["metadata"]);
        }
        return new ParseResult(/** @type {Partial<ParseResult>} */($$parsedSource));
    }
}

export class TabRecord {
    /**
     * Creates a new TabRecord instance.
     * @param {Partial<TabRecord>} [$$source = {}] - The source object to create the TabRecord.
     */
    constructor($$source = {}) {
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("isDirty" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isDirty"] = false;
        }
        if (!("pinned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pinned"] = false;
        }
        if (!("tabOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tabOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TabRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TabRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TabRecord(/** @type {Partial<TabRecord>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = TabRecord.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = FileNode.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
