// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../pkg/settings/models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigPath() {
    return $Call.ByID(1539290733);
}

/**
 * @returns {$CancellablePromise<settings$0.Settings | null>}
 */
export function Load() {
    return $Call.ByID(1749153376).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function OnTrayToggle(fn) {
    return $Call.ByID(744262157, fn);
}

/**
 * @param {settings$0.Settings | null} updated
 * @returns {$CancellablePromise<void>}
 */
export function Save(updated) {
    return $Call.ByID(495911033, updated);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function UpdateAutoStart(enabled) {
    return $Call.ByID(1192291182, enabled);
}

/**
 * @param {string} lang
 * @returns {$CancellablePromise<void>}
 */
export function UpdateLanguage(lang) {
    return $Call.ByID(988513459, lang);
}

/**
 * @param {string} theme
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTheme(theme) {
    return $Call.ByID(1766392858, theme);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTrayEnabled(enabled) {
    return $Call.ByID(2160789582, enabled);
}

// Private type creation functions
const $$createType0 = settings$0.Settings.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
