// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * "light" | "dark"
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * "en" | "zh"
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("trayEnabled" in $$source)) {
            /**
             * minimize to tray on close
             * @member
             * @type {boolean}
             */
            this["trayEnabled"] = false;
        }
        if (!("autoStart" in $$source)) {
            /**
             * launch on system startup
             * @member
             * @type {boolean}
             */
            this["autoStart"] = false;
        }
        if (!("windowWidth" in $$source)) {
            /**
             * last window width
             * @member
             * @type {number}
             */
            this["windowWidth"] = 0;
        }
        if (!("windowHeight" in $$source)) {
            /**
             * last window height
             * @member
             * @type {number}
             */
            this["windowHeight"] = 0;
        }
        if (!("windowX" in $$source)) {
            /**
             * last window X
             * @member
             * @type {number}
             */
            this["windowX"] = 0;
        }
        if (!("windowY" in $$source)) {
            /**
             * last window Y
             * @member
             * @type {number}
             */
            this["windowY"] = 0;
        }
        if (!("openTabs" in $$source)) {
            /**
             * session restore
             * @member
             * @type {TabSnapshot[]}
             */
            this["openTabs"] = [];
        }
        if (!("lastOpenFolder" in $$source)) {
            /**
             * restore file tree
             * @member
             * @type {string}
             */
            this["lastOpenFolder"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("openTabs" in $$parsedSource) {
            $$parsedSource["openTabs"] = $$createField8_0($$parsedSource["openTabs"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

export class TabSnapshot {
    /**
     * Creates a new TabSnapshot instance.
     * @param {Partial<TabSnapshot>} [$$source = {}] - The source object to create the TabSnapshot.
     */
    constructor($$source = {}) {
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("scrollPosition" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scrollPosition"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TabSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TabSnapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TabSnapshot(/** @type {Partial<TabSnapshot>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = TabSnapshot.createFrom;
const $$createType1 = $Create.Array($$createType0);
